chore(update): update packages (7)
changed: zen-browser-bin, lagrange, google-chrome, penguins-eggs, limine-snapper-sync, gallery-dl, limine-dracut-support

diff --git a/limine-dracut-support/PKGBUILD b/limine-dracut-support/PKGBUILD
--- a/limine-dracut-support/PKGBUILD
+++ b/limine-dracut-support/PKGBUILD
@@ -2,19 +2,20 @@
 _pkgname="limine-entry-tool"
 pkgname="limine-dracut-support"
 pkgver=1.22.1
-pkgrel=1
+pkgrel=2
 pkgdesc="Install kernel for the Limine bootloader."
 arch=("any")
 url="https://gitlab.com/Zesko/limine-entry-tool"
 source=("$_pkgname-$pkgver.tar.gz::$url/-/archive/$pkgver/$_pkgname-$pkgver.tar.gz")
 license=("GPL3")
 provides=('limine-entry-tool')
-_java_version=17
+_jre_version=17
+_jdk_version=21
 depends=(
   'bash'
   'grep'
   'tar'
-  'java-environment>='${_java_version}
+  'java-runtime-headless>='${_jre_version}
   'limine'
   'dracut'
   'efibootmgr')
@@ -23,38 +24,23 @@ optdepends=(
   'sbctl: Signs UEFI boot files for Secure Boot when enabled'
   'journalctl-desktop-notification: Sends desktop notifications when errors occur'
 )
-makedepends=('git' 'maven')
+makedepends=('git' 'jdk21-openjdk' 'maven')
 backup=(etc/limine-entry-tool.conf)
-conflicts=('limine-dracut-support-git' 'limine-entry-tool')
+conflicts=('limine-entry-tool')
 sha256sums=('7e705f4655989b99419fa5418f9102521cbe53706689392a4da76a8444613190')
 
-_check_java_version() {
-  local java_version
-  java_version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
-
-  if [[ -z "$java_version" ]]; then
-    echo "Error: Java version ${_java_version} is not installed or not set." >&2
-    echo "Please check with: 'archlinux-java status'"
-    echo "If java ${_java_version} or a newer version is installed, run 'archlinux-java set java-${_java_version}-openjdk' or a newer version."
-    return 1
-  fi
-
-  if [[ "$java_version" -lt ${_java_version} ]]; then
-    echo "Error: Java version $java_version is older than the required ${_java_version}."
-    echo "Please check with: 'archlinux-java status'"
-    echo "If java ${_java_version} or a newer version is installed, run 'archlinux-java set java-${_java_version}-openjdk' or a newer version."
+prepare() {
+  unset JAVA_OPTS JDK_JAVA_OPTIONS JAVA_TOOL_OPTIONS
+  JAVA_HOME=/usr/lib/jvm/java-${_jdk_version}-openjdk
+  if ! command -v ${JAVA_HOME}/bin/javac > /dev/null 2>&1; then
+    echo "Error: ${JAVA_HOME}/bin/javac not found." >&2
     return 1
   fi
 }
 
 build() {
-  unset JAVA_HOME JAVA_OPTS JDK_JAVA_OPTIONS JAVA_TOOL_OPTIONS
-  if _check_java_version; then
-    cd "$srcdir/${_pkgname}-${pkgver}"
-    mvn clean package
-  else
-    return 1
-  fi
+  cd "$srcdir/${_pkgname}-${pkgver}"
+  JAVA_HOME=/usr/lib/jvm/java-${_jdk_version}-openjdk mvn clean package
 }
 
 package() {
diff --git a/limine-snapper-sync/PKGBUILD b/limine-snapper-sync/PKGBUILD
--- a/limine-snapper-sync/PKGBUILD
+++ b/limine-snapper-sync/PKGBUILD
@@ -1,16 +1,17 @@
 # Maintainer: Zesko
 pkgname="limine-snapper-sync"
 pkgver=1.13.1
-pkgrel=1
+pkgrel=2
 pkgdesc="The tool syncs Limine snapshot entries with Snapper snapshots."
 arch=("any")
 url="https://gitlab.com/Zesko/limine-snapper-sync"
 source=("$pkgname-$pkgver.tar.gz::$url/-/archive/$pkgver/$pkgname-$pkgver.tar.gz")
 license=("GPL3")
-_java_version=17
+_jre_version=17
+_jdk_version=21
 depends=(
   'bash'
-  'java-environment>='${_java_version}
+  'java-runtime-headless>='${_jre_version}
   'limine'
   'snapper'
   'btrfs-progs'
@@ -24,38 +25,23 @@ optdepends=(
   'journalctl-desktop-notification: Sends desktop notifications for errors, including detected hardware issues.'
   'b3sum: Fast Blake3 hash function to prevent duplication.'
 )
-makedepends=('git' 'maven')
+makedepends=('git' 'jdk21-openjdk' 'maven')
 backup=(etc/limine-snapper-sync.conf)
 conflicts=('limine-snapper-sync-git')
 sha256sums=('647db0e3846dcb9bae2398dc53b6a00041dbc9ba60dfce309709f7fbbb24e784')
 
-check_java_version() {
-  local java_version
-  java_version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
-
-  if [[ -z "$java_version" ]]; then
-    echo "Error: Java version ${_java_version} is not installed or not set." >&2
-    echo "Please check with: 'archlinux-java status'"
-    echo "If java ${_java_version} or a newer version is installed, run 'archlinux-java set java-${_java_version}-openjdk' or a newer version."
-    return 1
-  fi
-
-  if [[ "$java_version" -lt ${_java_version} ]]; then
-    echo "Error: Java version $java_version is older than the required ${_java_version}." >&2
-    echo "Please check with: 'archlinux-java status'"
-    echo "If java ${_java_version} or a newer version is installed, run 'archlinux-java set java-${_java_version}-openjdk' or a newer version."
+prepare() {
+  unset JAVA_OPTS JDK_JAVA_OPTIONS JAVA_TOOL_OPTIONS
+  JAVA_HOME=/usr/lib/jvm/java-${_jdk_version}-openjdk
+  if ! command -v ${JAVA_HOME}/bin/javac > /dev/null 2>&1; then
+    echo "Error: ${JAVA_HOME}/bin/javac not found." >&2
     return 1
   fi
 }
 
 build() {
-  unset JAVA_HOME JAVA_OPTS JDK_JAVA_OPTIONS JAVA_TOOL_OPTIONS
-  if check_java_version; then
-    cd "$srcdir/${pkgname}-${pkgver}"
-    mvn clean package
-  else
-    return 1
-  fi
+  cd "$srcdir/${pkgname}-${pkgver}"
+  JAVA_HOME=/usr/lib/jvm/java-${_jdk_version}-openjdk mvn clean package
 }
 
 package() {
