chore(update): reshade-shaders-git

diff --git a/reshade-shaders-git/PKGBUILD b/reshade-shaders-git/PKGBUILD
--- a/reshade-shaders-git/PKGBUILD
+++ b/reshade-shaders-git/PKGBUILD
@@ -1,15 +1,18 @@
 # Maintainer: billli11
+# Contributor: marmis
+# Contributor: gee
 
 pkgname=reshade-shaders-git
-pkgver=r81.fe1771a
+pkgver=r118.67603ed
 pkgrel=1
 pkgdesc='A collection of post-processing shaders written in the ReShade FX shader language, to be used by vkBasalt'
 arch=('any')
 url='https://github.com/crosire/reshade-shaders'
 license=('custom')
-makedepends=('git' 'curl' 'libarchive')
+makedepends=('git' 'curl' 'libarchive' 'parallel')
 source=("git+https://github.com/crosire/reshade-shaders.git#branch=list")
 sha256sums=(SKIP)
+options=(!strip)
 install=reshade-shaders.install
 
 pkgver() {
@@ -18,52 +21,17 @@ pkgver() {
 }
 
 build() {
-  local -A ini_array
-  local -a effect_lists
-  local line effect license shaders textures
-
   [ -d "${srcdir}/build" ] && rm -r "${srcdir}/build"
   mkdir -p "${srcdir}/build/"{shaders,textures,extract}
   cd "${srcdir}/build"
 
-  {
+  extract_effect() {
+    local -A ini_array
+    local line license shaders textures
+
     read -r
     while read -r line; do
       case "$line" in
-        "["*"]")
-          # Set fallback name if empty
-          ini_array[name]="${ini_array[name]:-${ini_array[url]##*/}}"
-          ini_array[shaders]="${ini_array[shaders]:-shaders}"
-          ini_array[textures]="${ini_array[textures]:-textures}"
-
-          msg "Getting ${ini_array[name]}"
-          mkdir -p "extract/${ini_array[name]}" "${ini_array[shaders]}" "${ini_array[textures]}"
-
-          (
-            cd "extract/${ini_array[name]}"
-            if ! /usr/bin/curl -L "${ini_array[url]}" -o "${ini_array[name]}.zip"; then
-              msg "Failed to download ${ini_array[url]}"
-              exit 1
-            fi
-            if ! /usr/bin/bsdunzip "${ini_array[name]}.zip"; then
-              msg "Failed to extract ${ini_array[name]}.zip"
-              exit 1
-            fi
-
-            shaders="$(find . -mindepth 1 -type d -iname 'shaders' | head -n 1)"
-            [ -d "$shaders" ] && mv "$shaders/"* -t "../../${ini_array[shaders]}"
-
-            while read -d '' -r license; do
-              mv "$license" -t "../../${ini_array[shaders]}"
-            done < <(find . -type f -iregex '.*/\(license.*\|.*\.md\)' -print0)
-
-            textures="$(find . -mindepth 1 -type d -iname 'textures' | head -n 1)"
-            [ -d "$textures" ] && mv "$textures/"* -t "../../${ini_array[textures]}"
-
-            msg done
-          )
-          unset "ini_array[name]" "ini_array[shaders]" "ini_array[textures]" "ini_array[url]"
-          ;;
         "PackageName="*)
           ini_array[name]="${line#PackageName=}"
           ;;
@@ -82,7 +50,46 @@ build() {
           ;;
       esac
     done
-  } < <(cat ../reshade-shaders/EffectPackages.ini <(echo '[end]'))
+
+    # Set fallback name if empty
+    ini_array[name]="${ini_array[name]:-${ini_array[url]##*/}}"
+    ini_array[shaders]="${ini_array[shaders]:-shaders}"
+    ini_array[textures]="${ini_array[textures]:-textures}"
+
+    msg "Getting ${ini_array[name]}"
+    mkdir -p "extract/${ini_array[name]}" "${ini_array[shaders]}" "${ini_array[textures]}"
+
+    (
+      cd "extract/${ini_array[name]}"
+      if ! /usr/bin/curl -L "${ini_array[url]}" -o "${ini_array[name]}.zip"; then
+        error "Failed to download ${ini_array[url]}"
+        exit 1
+      fi
+      if ! /usr/bin/bsdunzip "${ini_array[name]}.zip"; then
+        error "Failed to extract ${ini_array[name]}.zip"
+        exit 1
+      fi
+
+      shaders="$(find . -mindepth 1 -type d -iname 'shaders' | head -n 1)"
+      [ -d "$shaders" ] && mv "$shaders/"* -t "../../${ini_array[shaders]}"
+
+      while read -d '' -r license; do
+        mv "$license" -t "../../${ini_array[shaders]}"
+      done < <(find . -type f -iregex '.*/\(license.*\|.*\.md\)' -print0)
+
+      textures="$(find . -mindepth 1 -type d -iname 'textures' | head -n 1)"
+      [ -d "$textures" ] && mv "$textures/"* -t "../../${ini_array[textures]}"
+
+      msg done
+    )
+  }
+
+  export -f extract_effect msg error
+  export ALL_OFF BOLD BLUE GREEN RED YELLOW
+
+  cat ../reshade-shaders/EffectPackages.ini \
+    | SHELL=$(type -p bash) parallel -N1 --pipe --regexp --recstart '^\[[^\]]*\]' \
+      extract_effect
 }
 
 package() {
