chore(update): packages (18)
android-platform, babashka-bin, ferdium-nightly-bin, gonic, jackett, ludusavi, oblivion-desktop, oh-my-posh-bin, peazip, plasma6-applets-panel-colorizer, polychromatic, qownnotes, qt6gtk2, signal-desktop-beta, subtitleedit, vscodium-electron, xnconvert, zen-browser-bin

diff --git a/vscodium-electron/vscodium-electron.patch b/vscodium-electron/vscodium-electron.patch
--- a/vscodium-electron/vscodium-electron.patch
+++ b/vscodium-electron/vscodium-electron.patch
@@ -1,13 +1,10 @@
 diff --git a/build.sh b/build.sh
-index 6ed4d4b..b6ed77d 100755
+index 834ac4c..dcd040a 100755
 --- a/build.sh
 +++ b/build.sh
-@@ -10,9 +10,16 @@ if [[ "${SHOULD_BUILD}" == "yes" ]]; then
+@@ -12,7 +12,14 @@ if [[ "${SHOULD_BUILD}" == "yes" ]]; then
  
-   . prepare_vscode.sh
- 
--  cd vscode || { echo "'vscode' dir not found"; exit 1; }
-+  cd vscode || { echo "Failed to get vscode sources."; exit 1; }
+   cd vscode || { echo "'vscode' dir not found"; exit 1; }
  
 -  export NODE_OPTIONS="--max-old-space-size=8192"
 +  # Build native modules for system electron
@@ -19,55 +16,65 @@ index 6ed4d4b..b6ed77d 100755
 +  # Thus, replace the checksum file with the one for the system version
 +  curl -L https://github.com/electron/electron/releases/download/v$_target/SHASUMS256.txt > build/checksums/electron.txt
  
-   yarn monaco-compile-check
-   yarn valid-layers-check
-@@ -22,49 +29,9 @@ if [[ "${SHOULD_BUILD}" == "yes" ]]; then
-   yarn gulp compile-extensions-build
-   yarn gulp minify-vscode
+   npm run monaco-compile-check
+   npm run valid-layers-check
+@@ -22,58 +29,11 @@ if [[ "${SHOULD_BUILD}" == "yes" ]]; then
+   npm run gulp compile-extensions-build
+   npm run gulp minify-vscode
  
 -  if [[ "${OS_NAME}" == "osx" ]]; then
--    yarn gulp "vscode-darwin-${VSCODE_ARCH}-min-ci"
-+  yarn gulp "vscode-linux-${VSCODE_ARCH}-min-ci"
+-    # generate Group Policy definitions
+-    node build/lib/policies darwin
++  npm run gulp "vscode-linux-${VSCODE_ARCH}-min-ci"
+ 
+-    npm run gulp "vscode-darwin-${VSCODE_ARCH}-min-ci"
++  . ../build_cli.sh
  
 -    find "../VSCode-darwin-${VSCODE_ARCH}" -print0 | xargs -0 touch -c
+-
+-    . ../build_cli.sh
 -
 -    VSCODE_PLATFORM="darwin"
 -  elif [[ "${OS_NAME}" == "windows" ]]; then
 -    # generate Group Policy definitions
--    node build/lib/policies
+-    node build/lib/policies win32
 -
 -    # in CI, packaging will be done by a different job
 -    if [[ "${CI_BUILD}" == "no" ]]; then
 -      . ../build/windows/rtf/make.sh
 -
--      yarn gulp "vscode-win32-${VSCODE_ARCH}-min-ci"
+-      npm run gulp "vscode-win32-${VSCODE_ARCH}-min-ci"
 -
 -      if [[ "${VSCODE_ARCH}" != "x64" ]]; then
 -        SHOULD_BUILD_REH="no"
 -        SHOULD_BUILD_REH_WEB="no"
 -      fi
+-
+-      . ../build_cli.sh
 -    fi
 -
 -    VSCODE_PLATFORM="win32"
 -  else # linux
 -    # in CI, packaging will be done by a different job
 -    if [[ "${CI_BUILD}" == "no" ]]; then
--      yarn gulp "vscode-linux-${VSCODE_ARCH}-min-ci"
+-      npm run gulp "vscode-linux-${VSCODE_ARCH}-min-ci"
 -
 -      find "../VSCode-linux-${VSCODE_ARCH}" -print0 | xargs -0 touch -c
+-
+-      . ../build_cli.sh
 -    fi
 -
 -    VSCODE_PLATFORM="linux"
 -  fi
 -
 -  if [[ "${SHOULD_BUILD_REH}" != "no" ]]; then
--    yarn gulp minify-vscode-reh
--    yarn gulp "vscode-reh-${VSCODE_PLATFORM}-${VSCODE_ARCH}-min-ci"
+-    npm run gulp minify-vscode-reh
+-    npm run gulp "vscode-reh-${VSCODE_PLATFORM}-${VSCODE_ARCH}-min-ci"
 -  fi
 -
 -  if [[ "${SHOULD_BUILD_REH_WEB}" != "no" ]]; then
--    yarn gulp minify-vscode-reh-web
--    yarn gulp "vscode-reh-web-${VSCODE_PLATFORM}-${VSCODE_ARCH}-min-ci"
+-    npm run gulp minify-vscode-reh-web
+-    npm run gulp "vscode-reh-web-${VSCODE_PLATFORM}-${VSCODE_ARCH}-min-ci"
 -  fi
 +  echo "Skipping build of REH (Remote Extension Host)."
  
