chore(update): ipfs-desktop

diff --git a/ipfs-desktop/PKGBUILD b/ipfs-desktop/PKGBUILD
--- a/ipfs-desktop/PKGBUILD
+++ b/ipfs-desktop/PKGBUILD
@@ -1,22 +1,33 @@
 # Maintainer: @RubenKelevra <rubenkelevra@gmail.com>
 # Contributor: Alex Henrie <alexhenrie24@gmail.com>
 
-_electron_pkg='electron43'
+_electron_pkg='electron44'
 _webui_cid='bafybeiciqeyipumpmhxzlxnbqdbbv6u5uij4hy4wax64dmj7kvrhusiq6y'
 
 pkgname='ipfs-desktop'
-pkgver='0.50.0'
-pkgrel=4
+pkgver='0.50.1'
+pkgrel=1
 epoch=1
 pkgdesc='Desktop client for the InterPlanetary File System'
 arch=('x86_64')
 url="https://github.com/ipfs/${pkgname}"
-license=('MIT')
+license=(
+  '0BSD'
+  'Apache-2.0'
+  'BSD-2-Clause'
+  'BSD-3-Clause'
+  'BlueOak-1.0.0'
+  'ISC'
+  'MIT'
+  'OFL-1.1'
+  'Python-2.0'
+)
 depends=(
   "${_electron_pkg}"
-  'kubo>=0.43.0'
+  'kubo>=0.43.1'
 )
 makedepends=(
+  'asar'
   'nodejs'
   'npm'
 )
@@ -25,16 +36,16 @@ source=(
   "webui-${_webui_cid}.car::https://trustless-gateway.link/ipfs/${_webui_cid}?format=car"
   "${pkgname}.desktop"
   "${pkgname}-startup.sh"
-  "${pkgname}-system-kubo-autostart.patch"
-  "${pkgname}-startup-race.patch"
+  'Inter-LICENSE.txt::https://raw.githubusercontent.com/rsms/inter/3ac1bd32a473ea60d40d8f444820247e96dd7e70/LICENSE.txt'
+  'Montserrat-OFL.txt::https://raw.githubusercontent.com/JulietaUla/Montserrat/fc12e6819947c76db917f9d589a1d327e37a7b6b/OFL.txt'
 )
 b2sums=(
-  'c5691c946de525abb185fa44ea66ff9c5fa15b936d3dd6e7d0c3a6da8b158e4b8c883b1d948c33e7333bf5e7def1fc6677c4c721a67956db56e817260db36cff'
+  'a58496e1bde4c28f64a6b97eed27a35c156e8c328485f6c950f9cd1772c3647d960d8972c63a824c88dfe31da4e3360352e93712589cd172a07da51595e37733'
   '49e1e7d4d55325d4ea05561a4ff4c64537988e5e841231a95d59328fc9f9b60f3098185bf757b70c42d2175f8a2b6394a0f2a9377df7d1603d69edbd4c3655ec'
   '849d57fd59653ed0c6eca01769ad12a01f37f6a5316f1a83c0bf7cae576074b978e3ca555d50a56114d177e5fe4817338106698716f054a3e18ae1c81d7a8785'
   'bb51f22c1cf58020bbb9d7f9dde2bfd6f838443130d89539c9ce2474f5a1987b332f63dd21b8a903880a77f96d58e8a868d0468e15d266357bdfe3409380eab2'
-  'c32bf5ac47328d78d72e0bd4d65bf21357d59208404a921e4cb9c5c78c48ece1fdedfef8e251c3e33613a37ee4cc6aa2fb0bc84e7aa57686664aa5f783b15ac5'
-  'cfe44691998e7c860dc7cb00cbd13688c8cb76a3da952a15f2df41de734f7e242dde18d8c6ee8a0c0c887091aec3198dbce898dd85862d5e4cb168bf05cd74d4'
+  '5417464983de312c9c2a250c64281d82c17fd531f78ceccaa44d97c6999a3faf61324eaaf588240a9d0f9319bb302b7d7ed88bdbc55c188efd0357645190690a'
+  '93047b82ab53aa80f1db73e4f9d0d2b2ac30fcee1be00b2b43c63a63da1ec41b32935acca720ed4b31d3cfd0e57d61faaf79be4951a90fa973312ab22e4f1488'
 )
 
 _pkgsrc="${pkgname}-${pkgver}"
@@ -85,8 +96,6 @@ prepare() (
   local _webui_path="${srcdir}/webui-${_webui_cid}"
 
   cd -- "${_pkgsrc}" || return 1
-  patch -Np1 -i "${srcdir}/${pkgname}-system-kubo-autostart.patch"
-  patch -Np1 -i "${srcdir}/${pkgname}-startup-race.patch"
 
   _expected_webui_cid=$(
     sed -nE \
@@ -158,13 +167,41 @@ build() {
 }
 
 package() {
+  local _license
+  local _packaged_app="${srcdir}/${pkgname}-packaged-app"
+
   mkdir -p -- "${pkgdir}/usr/lib/${pkgname}"
   cp -a -- "${_pkgsrc}/dist/linux-unpacked/resources/." "${pkgdir}/usr/lib/${pkgname}/"
+  rm -rf -- "${_packaged_app}"
+  asar extract "${_pkgsrc}/dist/linux-unpacked/resources/app.asar" "${_packaged_app}"
+  [[ -d "${_packaged_app}/node_modules" ]] || {
+    printf '%s\n' 'Packaged application is missing node_modules' >&2
+    return 1
+  }
+  [[ -d "${_packaged_app}/assets/webui/static/js" ]] || {
+    printf '%s\n' 'Packaged application is missing WebUI JavaScript assets' >&2
+    return 1
+  }
 
   install -Dm644 -- "${_pkgsrc}/assets/webui/ipfs-logo-512-ice.png" \
     "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
   install -Dm644 -- "${_pkgsrc}/LICENSE" \
     "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  for _license in 'Inter-LICENSE.txt' 'Montserrat-OFL.txt'; do
+    install -Dm644 -- "${srcdir}/${_license}" \
+      "${pkgdir}/usr/share/licenses/${pkgname}/webui/${_license}"
+  done
+
+  while IFS= read -r -d '' _license; do
+    install -Dm644 -- "${_license}" \
+      "${pkgdir}/usr/share/licenses/${pkgname}/${_license#"${_packaged_app}/"}"
+  done < <(find "${_packaged_app}/node_modules" -type f \
+    \( -iname 'license*' -o -iname 'copying*' -o -iname 'notice*' \) -print0)
+  while IFS= read -r -d '' _license; do
+    install -Dm644 -- "${_license}" \
+      "${pkgdir}/usr/share/licenses/${pkgname}/webui/${_license##*/}"
+  done < <(find "${_packaged_app}/assets/webui/static/js" -maxdepth 1 -type f \
+    -name '*.LICENSE.txt' -print0)
 
   sed "s|@ELECTRON_PKG@|${_electron_pkg}|" \
     "${srcdir}/${pkgname}-startup.sh" \
