chore(update): goofcord-bin

diff --git a/goofcord-bin/PKGBUILD b/goofcord-bin/PKGBUILD
--- a/goofcord-bin/PKGBUILD
+++ b/goofcord-bin/PKGBUILD
@@ -1,9 +1,9 @@
 # Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
 pkgname=goofcord-bin
 _pkgname=GoofCord
-pkgver=2.2.1
-_electronversion=41
-pkgrel=2
+pkgver=2.2.2
+_electronversion=43
+pkgrel=1
 pkgdesc="Take control of your Discord experience with GoofCord – the highly configurable and privacy first discord client.(Prebuilt version.Use system-wide electron)"
 arch=(
   'aarch64'
@@ -29,28 +29,21 @@ source_armv7h=("${pkgname%-bin}-${pkgver}-armv7h.rpm::${url}/releases/download/v
 source_x86_64=("${pkgname%-bin}-${pkgver}-x86_64.rpm::${url}/releases/download/v${pkgver}/${_pkgname}-${pkgver}-linux-x86_64.rpm")
 sha256sums=('4e7f66aa93929feee2db20f14f871e7ddcc69236b0ecfb79a19ade9b859daf51'
   'a774c2f54fbbeeaac3cefc0f7250796d30c86d27f0fd40b7eaf9c0fdb021623d')
-sha256sums_aarch64=('bf07bea484cfaa7fe3bbd59de87f6331e3448ad3b956ee910d218b31e8fd9868')
-sha256sums_armv7h=('1d04f327d83bebaf6afc5f4c9799a6e3a5dc5e1a67470de9a3388270b71f7d72')
-sha256sums_x86_64=('5c7ab33827c55b3cd6dc9fcc38c9475f3c72b1d26c9da9761df377d27fbf2d51')
+sha256sums_aarch64=('720eb805de0be2257c7c0b37fc5edb2917da7cde52028c1c91444da2e0c6e5bd')
+sha256sums_armv7h=('4db2eaa1663fd9d2b8b48dba83d6c3bdf2e02fb116c5244671630f82b94007c3')
+sha256sums_x86_64=('cec768b2342cb09aabd8a5a200eb8ee81cfb282fc1d74bd81c20f3a9b32d335a')
+_get_app_dir() {
+  find "${srcdir}" -type f -name "resources.pak" -exec dirname {} + | head -n 1
+}
 _check_electron_version() {
   echo "Verifying Electron version..."
-  local _app_dir=$(find "${srcdir}" -type f -name "resources.pak" -exec dirname {} + | head -n 1)
-  local _main_exe=""
-  if [[ -n "${_app_dir}" ]]; then
-    _main_exe=$(find "${_app_dir}" -maxdepth 1 -type f -executable -printf '%s %p\n' | sort -nr | head -n 1 | cut -d' ' -f2-)
-  fi
-  if [[ -n "${_main_exe}" ]]; then
-    local _elec_ver=$(strings "${_main_exe}" | grep '^Chrome/[0-9.]* Electron/[0-9]' | cut -d'/' -f3 | cut -d'.' -f1 | head -n 1)
-    if [[ -n "${_elec_ver}" ]]; then
-      if [[ "${_elec_ver}" != "${_electronversion}" ]]; then
-        echo -e "\033[1;31mWarning: Electron version mismatch! Detected: ${_elec_ver}, Expected: ${_electronversion}\033[0m"
-      else
-        echo -e "Electron version verified: \033[1;31m${_elec_ver}\033[0m"
-      fi
-    fi
-  else
-    echo -e "\033[1;33mNote: Could not find Electron binary for version verification.\033[0m"
-  fi
+  local _main_exe=$(find "$(_get_app_dir)" -maxdepth 1 -type f -executable -printf '%s %p\n' | sort -nr | head -1 | cut -d' ' -f2-)
+  [[ -z "${_main_exe}" ]] && echo -e "\033[1;33mNote: Could not find Electron binary.\033[0m" && return
+  local _elec_ver=$(strings "${_main_exe}" | grep -oP 'Electron/\K[0-9]+' | head -1)
+  [[ -z "${_elec_ver}" ]] && echo -e "\033[1;33mNote: Could not determine Electron version.\033[0m" && return
+  [[ "${_elec_ver}" != "${_electronversion}" ]] \
+    && echo -e "\033[1;31mWarning: Electron version mismatch! Detected: ${_elec_ver}, Expected: ${_electronversion}\033[0m" \
+    || echo -e "Electron version verified: \033[1;31m${_elec_ver}\033[0m"
 }
 prepare() {
   sed -i -e "
@@ -62,20 +55,22 @@ prepare() {
     " "${srcdir}/${pkgname%-bin}.sh"
   _check_electron_version
   sed -i "s/\/opt\/${_pkgname}\///g" "${srcdir}/usr/share/applications/${pkgname%-bin}.desktop"
-  asar e "${srcdir}/opt/${_pkgname}/resources/app.asar" "${srcdir}/app.asar.unpacked"
-  rm -rf "${srcdir}/opt/${_pkgname}/resources/app.asar"
+  local _app_dir=$(_get_app_dir)
+  asar e "${_app_dir}/resources/app.asar" "${srcdir}/app.asar.unpacked"
+  rm -rf "${_app_dir}/resources/app.asar"
   find "${srcdir}/app.asar.unpacked/ts-out" -type f -exec sed -i "s/process.resourcesPath/\'\/usr\/lib\/${pkgname%-bin}\'/g" {} +
-  asar p "${srcdir}/app.asar.unpacked" "${srcdir}/opt/${_pkgname}/resources/app.asar"
+  asar p "${srcdir}/app.asar.unpacked" "${_app_dir}/resources/app.asar"
 }
 package() {
   install -Dm755 "${srcdir}/${pkgname%-bin}.sh" "${pkgdir}/usr/bin/${pkgname%-bin}"
   install -Dm755 -d "${pkgdir}/usr/lib/${pkgname%-bin}"
-  local _app_dir=$(find "${srcdir}" -type f -name "resources.pak" -exec dirname {} + | head -n 1)
+  local _app_dir=$(_get_app_dir)
   cp -a "${_app_dir}/resources/". "${pkgdir}/usr/lib/${pkgname%-bin}/"
-  _icon_sizes=(16x16 32x32 48x48 64x64 128x128 256x256 512x512)
-  for _icons in "${_icon_sizes[@]}"; do
-    install -Dm644 "${srcdir}/usr/share/icons/hicolor/${_icons}/apps/${pkgname%-bin}.png" \
-      -t "${pkgdir}/usr/share/icons/hicolor/${_icons}/apps"
+  find "${srcdir}" -type f \( -name "*.png" -o -name "*.svg" \) -path "*share/icons/*" | while read -r _i; do
+    _extension="${_i##*.}"
+    _icon_path="${_i#*share/icons/}"
+    _target_dir="/usr/share/icons/$(dirname "${_icon_path}")"
+    install -Dm644 "${_i}" "${pkgdir}${_target_dir}/${pkgname%-bin}.${_extension}"
   done
   install -Dm644 "${srcdir}/usr/share/applications/${pkgname%-bin}.desktop" -t "${pkgdir}/usr/share/applications"
   install -Dm644 "${srcdir}/LICENSE-${pkgver}" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
