chore(update): mongodb, vital-synth, hyprland-qtutils-git

diff --git a/vital-synth/PKGBUILD b/vital-synth/PKGBUILD
--- a/vital-synth/PKGBUILD
+++ b/vital-synth/PKGBUILD
@@ -1,21 +1,67 @@
-maintainer=user981257923
+# Maintainer: user981257923
 pkgname=vital-synth
 pkgver=1.5.5
-pkgrel=3
-pkgdesc="Spectral warping wavetable synth."
-# arch=('x86_64' 'i686')
+pkgrel=5
+pkgdesc="Spectral warping wavetable synth. Manual download of .deb installer required."
 arch=('x86_64')
 url="https://vital.audio"
 license=('custom')
 provides=('vital')
-# groups=('pro-audio' 'lv2-plugins' 'vst-plugins' 'vst3-plugins')
 depends=('alsa-lib>=1.0.16' 'freetype2>=2.2.1' 'gcc-libs' 'gcc>=3.3.1' 'glib2>=2.12.0' 'glibc>=2.17' 'libcurl-gnutls>=7.16.2' 'libgl' 'libglvnd' 'libsecret>=0.7' 'zenity')
-# optdepends=('aarch64-linux-gnu-gcc>=5: support for aarch64')
-# options=('!strip' '!emptydirs')
 install=${pkgname}.install
-pkgname_deb="VitalInstaller"
-source_x86_64=("${pkgname}-${pkgver}-${pkgrel}.deb::https://github.com/bonecountysheriff/${pkgname_deb}/releases/download/${pkgver}-${pkgrel}/${pkgname_deb}.deb")
-sha512sums_x86_64=('b0a118d04989f5fb8a64dc5651cfd22f0a2e6742f4f7b805a3e317b336189eca9aa3bd9afb444c0d8c2b62dad1904ab57df6695144692497ca7faabbc50c1e17')
+
+pkgname_deb="VitalInstaller"      # The base name of the .deb file
+filename_deb="${pkgname_deb}.deb" # The full filename expected
+versioned_filename_deb="${pkgname_deb}-${pkgver}.deb"
+
+prepare() {
+
+  echo "The AUR moderators have prohibited mirroring ${filename_deb}, so unfortunately \
+the users will now be required to manually download the file on their own \
+from ${url}."
+
+  # Check if the .deb source file already exists in the srcdir (PKGBUILD directory)
+  if [[ ! -f "${srcdir}/${versioned_filename_deb}" ]]; then
+    echo "Please select the '${filename_deb}' file you manually downloaded from ${url} in the dialog box. \
+If you haven't done so already, cancel the dialog, download the file and run the setup again."
+
+    local downloaded_file=""
+    downloaded_file=$(zenity --file-selection \
+      --title="Select '${filename_deb}' for Vital Synth" \
+      --text="Please select the '${filename_deb}' file you manually downloaded from ${url}." \
+      --file-filter="*.deb" \
+      --file-filter="${filename_deb}")
+
+    if [[ -z "${downloaded_file}" ]]; then
+      error "No file selected. Aborting build."
+      exit 1
+    fi
+
+    if [[ "$(basename "${downloaded_file}")" != "${filename_deb}" ]]; then
+      error "Selected file is not '${filename_deb}'. Please select the correct file."
+      exit 1
+    fi
+
+    # Copy the selected file to the source directory expected by makepkg
+    msg "Copying '${downloaded_file}' to '${srcdir}/${versioned_filename_deb}'..."
+    cp "${downloaded_file}" "${srcdir}/${versioned_filename_deb}"
+  fi
+
+  # Extract the contents of the .deb file
+  msg "Extracting contents of ${versioned_filename_deb}..."
+  cd "${srcdir}"
+  ar x "${srcdir}/${versioned_filename_deb}"
+
+  # Extract data.tar.gz (the actual package contents)
+  if [[ -f "data.tar.gz" ]]; then
+    tar xzf data.tar.gz
+  elif [[ -f "data.tar.xz" ]]; then # In case it's xz compression
+    tar xJf data.tar.xz
+  else
+    error "Could not find data.tar.gz or data.tar.xz inside ${versioned_filename_deb}. Please check the .deb file."
+    exit 1
+  fi
+}
 
 package() {
   # echo $pkgdir
