chore(update): update packages (7)
changed: mullvad-vpn-cli, transset-df, mullvad-vpn-beta, mullvad-vpn, mise, brave-bin, betterbird-bin

diff --git a/mullvad-vpn-cli/mullvad-vpn.install b/mullvad-vpn-cli/mullvad-vpn.install
--- a/mullvad-vpn-cli/mullvad-vpn.install
+++ b/mullvad-vpn-cli/mullvad-vpn.install
@@ -1,12 +1,14 @@
 pre_install() {
-  if systemctl status mullvad-daemon &> /dev/null; then
-    echo 'Stopping & disabling Mullvad VPN daemon...'
-    /opt/Mullvad\ VPN/resources/mullvad-setup prepare-restart || true
-    systemctl disable --now mullvad-daemon
-    echo 'Disabling Mullvad early boot blocking service...'
-    systemctl disable mullvad-early-boot-blocking.service || true
-    cp /var/log/mullvad-vpn/daemon.log /var/log/mullvad-vpn/old-install-daemon.log \
-      || echo "Failed to copy old daemon log"
+  if which systemctl &> /dev/null && systemctl is-system-running | grep -vq offline &> /dev/null; then
+    if systemctl status mullvad-daemon &> /dev/null; then
+      echo 'Stopping & disabling Mullvad VPN daemon...'
+      /opt/Mullvad\ VPN/resources/mullvad-setup prepare-restart || true
+      systemctl disable --now mullvad-daemon
+      echo 'Disabling Mullvad early boot blocking service...'
+      systemctl disable mullvad-early-boot-blocking.service || true
+      cp /var/log/mullvad-vpn/daemon.log /var/log/mullvad-vpn/old-install-daemon.log \
+        || echo "Failed to copy old daemon log"
+    fi
   fi
 
   rm -f /var/cache/mullvad-vpn/relays.json
@@ -16,10 +18,12 @@ pre_install() {
 post_install() {
   chmod u+s "/usr/bin/mullvad-exclude"
 
-  echo 'Starting & enabling Mullvad VPN daemon...'
-  systemctl enable --now mullvad-daemon || echo "Failed to start mullvad-daemon.service"
-  echo 'Enabling Mullvad early boot blocking service...'
-  systemctl enable mullvad-early-boot-blocking
+  if which systemctl &> /dev/null && systemctl is-system-running | grep -vq offline &> /dev/null; then
+    echo 'Starting & enabling Mullvad VPN daemon...'
+    systemctl enable --now mullvad-daemon || echo "Failed to start mullvad-daemon.service"
+    echo 'Enabling Mullvad early boot blocking service...'
+    systemctl enable mullvad-early-boot-blocking
+  fi
 }
 
 pre_upgrade() {
@@ -27,16 +31,20 @@ pre_upgrade() {
 }
 
 post_upgrade() {
-  systemctl daemon-reload
+  if which systemctl &> /dev/null && systemctl is-system-running | grep -vq offline &> /dev/null; then
+    systemctl daemon-reload
+  fi
 
   post_install
 }
 
 pre_remove() {
   # the user might've disabled or stopped the services themselves already
-  echo 'Making sure the services are stopped & disabled...'
-  systemctl disable --now mullvad-daemon || true
-  systemctl disable --now mullvad-early-boot-blocking.service || true
+  if which systemctl &> /dev/null && systemctl is-system-running | grep -vq offline &> /dev/null; then
+    echo 'Making sure the services are stopped & disabled...'
+    systemctl disable --now mullvad-daemon || true
+    systemctl disable --now mullvad-early-boot-blocking.service || true
+  fi
 
   /opt/Mullvad\ VPN/resources/mullvad-setup reset-firewall || echo "Failed to reset firewall"
   /opt/Mullvad\ VPN/resources/mullvad-setup remove-device || echo "Failed to remove device from account"
