chore(update): update packages (5)
changed: oh-my-posh-bin, mullvad-vpn-cli, mullvad-vpn-beta, python-telegram-bot, mullvad-vpn

diff --git a/mullvad-vpn-beta/mullvad-vpn.install b/mullvad-vpn-beta/mullvad-vpn.install
--- a/mullvad-vpn-beta/mullvad-vpn.install
+++ b/mullvad-vpn-beta/mullvad-vpn.install
@@ -19,9 +19,14 @@ post_install() {
   chmod u+s "/usr/bin/mullvad-exclude"
 
   echo 'Starting & enabling Mullvad VPN daemon...'
-  systemctl enable --now mullvad-daemon
+  systemctl enable --now mullvad-daemon || echo "Failed to start mullvad-daemon.service"
   echo 'Enabling Mullvad early boot blocking service...'
   systemctl enable mullvad-early-boot-blocking
+
+  # Reload apparmor profile
+  if [ -f "/usr/bin/apparmor_parser" ]; then
+    apparmor_parser -r /etc/apparmor.d/mullvad || echo "Failed to reload apparmor profile"
+  fi
 }
 
 pre_upgrade() {
diff --git a/mullvad-vpn-cli/mullvad-vpn.install b/mullvad-vpn-cli/mullvad-vpn.install
--- a/mullvad-vpn-cli/mullvad-vpn.install
+++ b/mullvad-vpn-cli/mullvad-vpn.install
@@ -17,7 +17,7 @@ post_install() {
   chmod u+s "/usr/bin/mullvad-exclude"
 
   echo 'Starting & enabling Mullvad VPN daemon...'
-  systemctl enable --now mullvad-daemon
+  systemctl enable --now mullvad-daemon || echo "Failed to start mullvad-daemon.service"
   echo 'Enabling Mullvad early boot blocking service...'
   systemctl enable mullvad-early-boot-blocking
 }
diff --git a/mullvad-vpn/mullvad-vpn.install b/mullvad-vpn/mullvad-vpn.install
--- a/mullvad-vpn/mullvad-vpn.install
+++ b/mullvad-vpn/mullvad-vpn.install
@@ -19,9 +19,14 @@ post_install() {
   chmod u+s "/usr/bin/mullvad-exclude"
 
   echo 'Starting & enabling Mullvad VPN daemon...'
-  systemctl enable --now mullvad-daemon
+  systemctl enable --now mullvad-daemon || echo "Failed to start mullvad-daemon.service"
   echo 'Enabling Mullvad early boot blocking service...'
   systemctl enable mullvad-early-boot-blocking
+
+  # Reload apparmor profile
+  if [ -f "/usr/bin/apparmor_parser" ]; then
+    apparmor_parser -r /etc/apparmor.d/mullvad || echo "Failed to reload apparmor profile"
+  fi
 }
 
 pre_upgrade() {
@@ -59,7 +64,7 @@ post_remove() {
   echo 'sudo rm -rf /etc/mullvad-vpn/'
   echo ''
   echo 'Optionally remove app settings:'
-  echo 'rm -rf ~/.config/Mullvad VPN/'
+  echo 'rm -rf ~/.config/Mullvad\ VPN/'
   echo ''
   echo 'Optionally remove auto-launcher:'
   echo 'rm ~/.config/autostart/mullvad-vpn.desktop'
